DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.app_settings) THEN
    UPDATE public.app_settings
    SET hourly_cost_fixed_items = '[{"id": "1", "name": "Pró-labore", "value": 8000}, {"id": "2", "name": "Salários Funcionários / Condução / Alimentação / Cesta Básica", "value": 22231.2}, {"id": "3", "name": "Exames Admissional / demissional", "value": 324.07}, {"id": "4", "name": "Provisionamento férias e 13º", "value": 1518}, {"id": "5", "name": "Rescisões", "value": 500}, {"id": "6", "name": "GPS", "value": 1711}, {"id": "7", "name": "FGTS", "value": 1843.99}, {"id": "8", "name": "Infinity", "value": 5187.75}, {"id": "9", "name": "Contabilidade", "value": 1100}, {"id": "10", "name": "Taxas: Licença / Lixo séptico / Publicidade", "value": 150}, {"id": "11", "name": "Assistência Juridica", "value": 0}, {"id": "12", "name": "CRO", "value": 86.75}, {"id": "13", "name": "Sindicatos", "value": 0}, {"id": "14", "name": "Uniforme", "value": 500}, {"id": "15", "name": "Segurança/ Alarme", "value": 267}, {"id": "16", "name": "Aluguel / IPTU / Condominio", "value": 4900}, {"id": "17", "name": "Energia / Água", "value": 0}, {"id": "18", "name": "Telefonia / Internet", "value": 871}, {"id": "19", "name": "Encargos bancários", "value": 0}, {"id": "20", "name": "Material Higiene / Limpeza", "value": 400}, {"id": "21", "name": "Dedetização", "value": 95}, {"id": "22", "name": "Manutenções: computadores (CPU) / Equipamentos Odontotológicos / Geral", "value": 390}, {"id": "23", "name": "Software", "value": 2764}, {"id": "24", "name": "Brindes / kit Higiene", "value": 280}, {"id": "25", "name": "Café e açucar (comes e bebes)", "value": 417}, {"id": "26", "name": "Gráfica", "value": 145.15}, {"id": "27", "name": "Site (dominio / hospedagem)", "value": 0}, {"id": "28", "name": "Marketing (empresa + patrocínio)", "value": 9248}, {"id": "29", "name": "Material escritório", "value": 100}, {"id": "30", "name": "Correios", "value": 31.8}, {"id": "31", "name": "Motoboy", "value": 0}, {"id": "32", "name": "Fundo de reserva", "value": 1000}, {"id": "33", "name": "Fundo de melhorias", "value": 1000}, {"id": "34", "name": "Dental", "value": 7948.33}, {"id": "35", "name": "Outros", "value": 0}]'::jsonb;
  ELSE
    INSERT INTO public.app_settings (hourly_cost_fixed_items)
    VALUES ('[{"id": "1", "name": "Pró-labore", "value": 8000}, {"id": "2", "name": "Salários Funcionários / Condução / Alimentação / Cesta Básica", "value": 22231.2}, {"id": "3", "name": "Exames Admissional / demissional", "value": 324.07}, {"id": "4", "name": "Provisionamento férias e 13º", "value": 1518}, {"id": "5", "name": "Rescisões", "value": 500}, {"id": "6", "name": "GPS", "value": 1711}, {"id": "7", "name": "FGTS", "value": 1843.99}, {"id": "8", "name": "Infinity", "value": 5187.75}, {"id": "9", "name": "Contabilidade", "value": 1100}, {"id": "10", "name": "Taxas: Licença / Lixo séptico / Publicidade", "value": 150}, {"id": "11", "name": "Assistência Juridica", "value": 0}, {"id": "12", "name": "CRO", "value": 86.75}, {"id": "13", "name": "Sindicatos", "value": 0}, {"id": "14", "name": "Uniforme", "value": 500}, {"id": "15", "name": "Segurança/ Alarme", "value": 267}, {"id": "16", "name": "Aluguel / IPTU / Condominio", "value": 4900}, {"id": "17", "name": "Energia / Água", "value": 0}, {"id": "18", "name": "Telefonia / Internet", "value": 871}, {"id": "19", "name": "Encargos bancários", "value": 0}, {"id": "20", "name": "Material Higiene / Limpeza", "value": 400}, {"id": "21", "name": "Dedetização", "value": 95}, {"id": "22", "name": "Manutenções: computadores (CPU) / Equipamentos Odontotológicos / Geral", "value": 390}, {"id": "23", "name": "Software", "value": 2764}, {"id": "24", "name": "Brindes / kit Higiene", "value": 280}, {"id": "25", "name": "Café e açucar (comes e bebes)", "value": 417}, {"id": "26", "name": "Gráfica", "value": 145.15}, {"id": "27", "name": "Site (dominio / hospedagem)", "value": 0}, {"id": "28", "name": "Marketing (empresa + patrocínio)", "value": 9248}, {"id": "29", "name": "Material escritório", "value": 100}, {"id": "30", "name": "Correios", "value": 31.8}, {"id": "31", "name": "Motoboy", "value": 0}, {"id": "32", "name": "Fundo de reserva", "value": 1000}, {"id": "33", "name": "Fundo de melhorias", "value": 1000}, {"id": "34", "name": "Dental", "value": 7948.33}, {"id": "35", "name": "Outros", "value": 0}]'::jsonb);
  END IF;
END $$;
