DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.app_settings) THEN
    INSERT INTO public.app_settings (hourly_cost_fixed_items, hourly_cost_monthly_hours)
    VALUES ('[
      {"id": "fc-1", "name": "Pró-labore", "label": "Pró-labore", "value": 8000.00},
      {"id": "fc-2", "name": "Salários Funcionários / Condução / Alimentação / Cesta Básica", "label": "Salários Funcionários / Condução / Alimentação / Cesta Básica", "value": 22231.20},
      {"id": "fc-3", "name": "Exames Admissional / demissional", "label": "Exames Admissional / demissional", "value": 324.07},
      {"id": "fc-4", "name": "Provisionamento férias e 13º", "label": "Provisionamento férias e 13º", "value": 1518.00},
      {"id": "fc-5", "name": "Rescisões", "label": "Rescisões", "value": 500.00},
      {"id": "fc-6", "name": "GPS", "label": "GPS", "value": 1711.00},
      {"id": "fc-7", "name": "FGTS", "label": "FGTS", "value": 1843.99},
      {"id": "fc-8", "name": "Infinity", "label": "Infinity", "value": 5187.75},
      {"id": "fc-9", "name": "Contabilidade", "label": "Contabilidade", "value": 1100.00},
      {"id": "fc-10", "name": "Taxas: Licença / Lixo séptico / Publicidade", "label": "Taxas: Licença / Lixo séptico / Publicidade", "value": 150.00},
      {"id": "fc-11", "name": "Assistência Juridica", "label": "Assistência Juridica", "value": 0.00},
      {"id": "fc-12", "name": "CRO", "label": "CRO", "value": 86.75},
      {"id": "fc-13", "name": "Sindicatos", "label": "Sindicatos", "value": 0.00},
      {"id": "fc-14", "name": "Uniforme", "label": "Uniforme", "value": 500.00},
      {"id": "fc-15", "name": "Segurança/ Alarme", "label": "Segurança/ Alarme", "value": 267.00},
      {"id": "fc-16", "name": "Aluguel / IPTU / Condominio", "label": "Aluguel / IPTU / Condominio", "value": 4900.00},
      {"id": "fc-17", "name": "Energia / Água", "label": "Energia / Água", "value": 0.00},
      {"id": "fc-18", "name": "Telefonia / Internet", "label": "Telefonia / Internet", "value": 871.00},
      {"id": "fc-19", "name": "Encargos bancários", "label": "Encargos bancários", "value": 0.00},
      {"id": "fc-20", "name": "Material Higiene / Limpeza", "label": "Material Higiene / Limpeza", "value": 400.00},
      {"id": "fc-21", "name": "Dedetização", "label": "Dedetização", "value": 95.00},
      {"id": "fc-22", "name": "Manutenções: computadores (CPU) / Equipamentos Odontotológicos / Geral", "label": "Manutenções: computadores (CPU) / Equipamentos Odontotológicos / Geral", "value": 390.00},
      {"id": "fc-23", "name": "Software", "label": "Software", "value": 2764.00},
      {"id": "fc-24", "name": "Brindes / kit Higiene", "label": "Brindes / kit Higiene", "value": 280.00},
      {"id": "fc-25", "name": "Café e açucar (comes e bebes)", "label": "Café e açucar (comes e bebes)", "value": 417.00},
      {"id": "fc-26", "name": "Gráfica", "label": "Gráfica", "value": 145.15},
      {"id": "fc-27", "name": "Site (dominio / hospedagem)", "label": "Site (dominio / hospedagem)", "value": 0.00},
      {"id": "fc-28", "name": "Marketing (empresa + patrocinio)", "label": "Marketing (empresa + patrocinio)", "value": 9248.00},
      {"id": "fc-29", "name": "Material escritório", "label": "Material escritório", "value": 100.00},
      {"id": "fc-30", "name": "Correios", "label": "Correios", "value": 31.80},
      {"id": "fc-31", "name": "Motoboy", "label": "Motoboy", "value": 0.00},
      {"id": "fc-32", "name": "Fundo de reserva", "label": "Fundo de reserva", "value": 1000.00},
      {"id": "fc-33", "name": "Fundo de melhorias", "label": "Fundo de melhorias", "value": 1000.00},
      {"id": "fc-34", "name": "Dental", "label": "Dental", "value": 7948.33},
      {"id": "fc-35", "name": "Outros", "label": "Outros", "value": 0.00}
    ]'::jsonb, 160);
  ELSE
    UPDATE public.app_settings
    SET hourly_cost_fixed_items = '[
      {"id": "fc-1", "name": "Pró-labore", "label": "Pró-labore", "value": 8000.00},
      {"id": "fc-2", "name": "Salários Funcionários / Condução / Alimentação / Cesta Básica", "label": "Salários Funcionários / Condução / Alimentação / Cesta Básica", "value": 22231.20},
      {"id": "fc-3", "name": "Exames Admissional / demissional", "label": "Exames Admissional / demissional", "value": 324.07},
      {"id": "fc-4", "name": "Provisionamento férias e 13º", "label": "Provisionamento férias e 13º", "value": 1518.00},
      {"id": "fc-5", "name": "Rescisões", "label": "Rescisões", "value": 500.00},
      {"id": "fc-6", "name": "GPS", "label": "GPS", "value": 1711.00},
      {"id": "fc-7", "name": "FGTS", "label": "FGTS", "value": 1843.99},
      {"id": "fc-8", "name": "Infinity", "label": "Infinity", "value": 5187.75},
      {"id": "fc-9", "name": "Contabilidade", "label": "Contabilidade", "value": 1100.00},
      {"id": "fc-10", "name": "Taxas: Licença / Lixo séptico / Publicidade", "label": "Taxas: Licença / Lixo séptico / Publicidade", "value": 150.00},
      {"id": "fc-11", "name": "Assistência Juridica", "label": "Assistência Juridica", "value": 0.00},
      {"id": "fc-12", "name": "CRO", "label": "CRO", "value": 86.75},
      {"id": "fc-13", "name": "Sindicatos", "label": "Sindicatos", "value": 0.00},
      {"id": "fc-14", "name": "Uniforme", "label": "Uniforme", "value": 500.00},
      {"id": "fc-15", "name": "Segurança/ Alarme", "label": "Segurança/ Alarme", "value": 267.00},
      {"id": "fc-16", "name": "Aluguel / IPTU / Condominio", "label": "Aluguel / IPTU / Condominio", "value": 4900.00},
      {"id": "fc-17", "name": "Energia / Água", "label": "Energia / Água", "value": 0.00},
      {"id": "fc-18", "name": "Telefonia / Internet", "label": "Telefonia / Internet", "value": 871.00},
      {"id": "fc-19", "name": "Encargos bancários", "label": "Encargos bancários", "value": 0.00},
      {"id": "fc-20", "name": "Material Higiene / Limpeza", "label": "Material Higiene / Limpeza", "value": 400.00},
      {"id": "fc-21", "name": "Dedetização", "label": "Dedetização", "value": 95.00},
      {"id": "fc-22", "name": "Manutenções: computadores (CPU) / Equipamentos Odontotológicos / Geral", "label": "Manutenções: computadores (CPU) / Equipamentos Odontotológicos / Geral", "value": 390.00},
      {"id": "fc-23", "name": "Software", "label": "Software", "value": 2764.00},
      {"id": "fc-24", "name": "Brindes / kit Higiene", "label": "Brindes / kit Higiene", "value": 280.00},
      {"id": "fc-25", "name": "Café e açucar (comes e bebes)", "label": "Café e açucar (comes e bebes)", "value": 417.00},
      {"id": "fc-26", "name": "Gráfica", "label": "Gráfica", "value": 145.15},
      {"id": "fc-27", "name": "Site (dominio / hospedagem)", "label": "Site (dominio / hospedagem)", "value": 0.00},
      {"id": "fc-28", "name": "Marketing (empresa + patrocinio)", "label": "Marketing (empresa + patrocinio)", "value": 9248.00},
      {"id": "fc-29", "name": "Material escritório", "label": "Material escritório", "value": 100.00},
      {"id": "fc-30", "name": "Correios", "label": "Correios", "value": 31.80},
      {"id": "fc-31", "name": "Motoboy", "label": "Motoboy", "value": 0.00},
      {"id": "fc-32", "name": "Fundo de reserva", "label": "Fundo de reserva", "value": 1000.00},
      {"id": "fc-33", "name": "Fundo de melhorias", "label": "Fundo de melhorias", "value": 1000.00},
      {"id": "fc-34", "name": "Dental", "label": "Dental", "value": 7948.33},
      {"id": "fc-35", "name": "Outros", "label": "Outros", "value": 0.00}
    ]'::jsonb;
  END IF;
END $$;
